# Generated by Django 2.1.7 on 2019-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('groupme_bot_id', models.CharField(max_length=30)),
                ('groupme_group_id', models.CharField(max_length=10)),
            ],
        ),
    ]
