# Generated by Django 2.1.7 on 2022-08-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200414_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
